# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dokan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Google-Mobile-Ads-SDK'

  # Add new pods below this line
  pod 'RNShare', :path => '../node_modules/react-native-share'

end
