# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Dokan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dokan
  pod 'Braintree'
  pod 'Bolts'
  pod 'FBSDKCoreKit', '4.38'
  pod 'FBSDKLoginKit', '4.38'
  pod 'FBSDKShareKit', '4.38'

  target 'DokanTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'Dokan-tvOS' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!

#   # Pods for Dokan-tvOS

#   target 'Dokan-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
